# Generated by Django 3.1.2 on 2020-10-10 19:18

import classes.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'), classes.models.Class.validate_comma_separated_weekday_list]),
        ),
    ]
