# Generated by Django 3.1.2 on 2020-10-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scholar_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='grade.grade'),
        ),
    ]
