# Generated by Django 3.1.2 on 2020-10-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('member', '0004_auto_20201013_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='departure_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='grade.grade'),
        ),
    ]
